
import { IconDashboard } from "@tabler/icons-react"
import {
  AreaChart,
  Award,
  BookOpen,
  BrainCircuit,
  Briefcase,
  Container,
  FileText,
  GraduationCap,
  Home,
  LucideLayoutDashboard,
  LucidePaperclip,
  Newspaper,
  PartyPopper,
  Scale,
  Search,
  Settings,
  Trophy,
  Upload,
  UserIcon,
  UserPen,
  UserPenIcon,
  Wallet,
  Users,
  BookMarked,
  Copyright,
  Lightbulb,
  Handshake,
  FlaskConical,
  Download,
  Paperclip,
  Car,
  Clock,
} from "lucide-react"
// This is sample data.


export const DashboardItems = [
  {
    title: "Dashboard",
    url: "#",
    icon: LucideLayoutDashboard,
    isActive: true,
    items: [
      { title: "Home", url: "/", icon: Home },
      { title: "Dashboard", url: "/dashboard", icon: IconDashboard },
      { title: "Upload Paper", url: "/dashboard/student/research-paper/upload", icon: Upload , access: ["STUDENT"]},
      { title: "Upload Project", url: "/dashboard/student/project/upload", icon: Upload , access: ["STUDENT"] },
      { title: "My Research Paper", url: "/dashboard/student/research-paper", icon: Paperclip, access: ["STUDENT"] },
      { title: "My Ongoing Project", url: "/dashboard/student/ongoing-project", icon: Clock, access: ["STUDENT"] },
      { title: "My Profile", url: "/dashboard/profile", icon: UserIcon },
    ],
  },
  {
    title: "Faculty Work Panel",
    url: "#",
    icon: AreaChart,
    access: ["FACULTY"],
    items: [
      { title: "Research Papers", icon: LucidePaperclip, url: "/dashboard/faculty/paper" },
      { title: "Ongoing Projects", icon: Container, url: "/dashboard/faculty/project" },
      { title: "Book Chapters", icon: BookOpen, url: "/dashboard/faculty/bookchapter" },
      { title: "Certifications", icon: Award, url: "/dashboard/faculty/certification" },
      { title: "Conferences", icon: Users, url: "/dashboard/faculty/conference" },
      { title: "Copyrights", icon: Copyright, url: "/dashboard/faculty/copyright" },
      { title: "FDPs", icon: GraduationCap, url: "/dashboard/faculty/fdp" },
      { title: "Grants", icon: Handshake, url: "/dashboard/faculty/grant" },
      { title: "Journals", icon: BookMarked, url: "/dashboard/faculty/journal" },
      { title: "Patents", icon: Lightbulb, url: "/dashboard/faculty/patent" },
      { title: "Transactions", icon: Wallet, url: "/dashboard/faculty/transaction" },
      { title: "Export Data", icon: Download, url: "/dashboard/faculty/export" },
    ],
  },
  {
    title: "Admin Work Panel",
    url: "#",
    icon: BrainCircuit,
    access: ["ADMIN"],
    items: [
      { title: "Teachers Management", url: "/dashboard/admin/teachers", icon: UserPenIcon },
      { title: "Students Management", url: "/dashboard/admin/students", icon: GraduationCap },
      { title: "User List", url: "/dashboard/admin/userlist", icon: UserIcon },
      { title: "Research Papers", url: "/dashboard/admin/research-papers", icon: LucidePaperclip },
      { title: "Ongoing Projects", url: "/dashboard/admin/ongoing-projects", icon: Container },
      { title: "Achievements", url: "/dashboard/admin/achievements", icon: Trophy },
      { title: "Competitions", url: "/dashboard/admin/competitions", icon: PartyPopper },
      { title: "Book Chapters", url: "/dashboard/admin/bookchapters", icon: BookOpen },
      { title: "Certifications", url: "/dashboard/admin/certifications", icon: Award },
      { title: "Conferences", url: "/dashboard/admin/conferences", icon: Users },
      { title: "Copyrights", url: "/dashboard/admin/copyrights", icon: Copyright },
      { title: "FDPs", url: "/dashboard/admin/fdps", icon: GraduationCap },
      { title: "Grants", url: "/dashboard/admin/grants", icon: Handshake },
      { title: "Journals", url: "/dashboard/admin/journals", icon: BookMarked },
      { title: "Patents", url: "/dashboard/admin/patents", icon: Lightbulb },
      { title: "Transactions", url: "/dashboard/admin/transactions", icon: Wallet },
    ],
  },
]

